name: push_notification_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  go_router: ^13.2.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  firebase_messaging: ^14.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
